//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raids.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class PIsp
    {
        public int Id { get; set; }
        public int IspId { get; set; }
        public int RpokazatelId { get; set; }
      
    }
}
